services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: uberdb
    volumes:
      - ./datasets:/datasets
    ports:
      - "3306:3306"
    networks:
      - global-net

networks:
  global-net:
    external: true
